"""inference: add timestamp, make user_id non-nullable

Revision ID: 54afea78c6bb
Revises: 3e12bcff6bf3
Create Date: 2025-11-23 18:22:32.678740

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54afea78c6bb"
down_revision: Union[str, Sequence[str], None] = "3e12bcff6bf3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("celebrities", sa.Column("img_path", sa.String(), nullable=False))
    op.drop_column("celebrities", "picture")
    op.drop_column("celebrities", "embedding")
    op.add_column("inferences", sa.Column("timestamp", sa.DateTime(), nullable=False))
    op.drop_column("inferences", "picture")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inferences", sa.Column("picture", sa.BLOB(), nullable=False))
    op.drop_column("inferences", "timestamp")
    op.add_column("celebrities", sa.Column("embedding", sa.BLOB(), nullable=True))
    op.add_column("celebrities", sa.Column("picture", sa.BLOB(), nullable=False))
    op.drop_column("celebrities", "img_path")
    # ### end Alembic commands ###
